INPUT_IMAGE_WIDTH = 1000 # 480
INPUT_IMAGE_HEIGHT = 1000 # 480
INPUT_IMAGE_SIZE = (INPUT_IMAGE_WIDTH, INPUT_IMAGE_HEIGHT)
MODEL_NAME = 'HEDSeg' # 'HEDSeg'
DATA_FOLDER = './HED-BSDS/' # './HED-BSDS/'
EPOCH_SIZE = 50 # 4096