INPUT_IMAGE_WIDTH = 800 # 480
INPUT_IMAGE_HEIGHT = 800 # 480
INPUT_IMAGE_SIZE = (INPUT_IMAGE_WIDTH, INPUT_IMAGE_HEIGHT)
MODEL_NAME = 'IHED' # 'HEDSeg'
DATA_FOLDER = './IHED-DATA/' # './HED-BSDS/'
EPOCH_SIZE = 10 # 4096
BATCH_SIZE = 1 # 10
CHECKPOINT = 'checkpoint.10-0.04.hdf5'